{
 "title": "Gitextractor Metrics",
 "description": "This dashboard shows the metrics thro",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "select concat(name, '--', id) as text from repos"
   }
  ]
 },
 "panels": [
  { "title": "file dimension", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "files with maximum number of authors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select file_path,count(distinct author_name) as cnt from commits join commit_files join repo_commits rc on commit_files.commit_sha = rc.commit_sha and  commit_files.commit_sha = commits.sha  where repo_id like $repo_id  group by file_path order by cnt desc limit 30;"
    }
   ]
  },
  {
   "title": "files with most modifications",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select file_path,count(*) as modified_num\nfrom commits join commit_files join repo_commits rc on commit_files.commit_sha = rc.commit_sha and  sha=commit_files.commit_sha \nwhere repo_id like $repo_id  group by file_path order by modified_num desc;"
    }
   ]
  },
  {
   "title": "largest files with lowest number of authors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select file_path,count(distinct author_name) as author_count, max(rst) as file_total_size from commits join (select file_path,commit_files.commit_sha, sum(additions) - sum(deletions) as rst from commit_files join repo_commits rc on commit_files.commit_sha = rc.commit_sha where repo_id like '%491450511%' group by file_path,commit_sha  order by rst desc ) a\n    on a.commit_sha = commits.sha group by file_path  having  author_count > 9 order by author_count asc  ,file_total_size  desc  limit 30 ;"
    }
   ]
  },
  {
   "title": "list files with most modifications",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "  select file_path,count(*) as cnt from commits join commit_files join repo_commits rc on commit_files.commit_sha = rc.commit_sha and  sha=commit_files.commit_sha where repo_id like '%%'  group by file_path order by cnt desc;"
    }
   ]
  },
  { "title": "author dimension", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "lines of code distribution by author",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select author_name,sum(additions-deletions) as cnt from commits join repo_commits where commits.sha =repo_commits.commit_sha and repo_commits.repo_id like $repo_id group by author_name,author_id order by cnt desc\n"
    }
   ]
  },
  {
   "title": "commits distribution by author",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "select author_name,count(distinct commit_sha) as commit_nums from commits join repo_commits where commits.sha =repo_commits.commit_sha and repo_commits.repo_id like $repo_id  group by author_name,author_id order by commit_nums desc;\n"
    }
   ]
  },
  {
   "title": "time perspective",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "lines of code distribution in a week; ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "select dayofweek(authored_date) as weekday ,sum(additions-deletions) as changed_nums,sum(additions) as total_additions,sum(deletions) as total_deletions from commits join repo_commits where commits.sha =repo_commits.commit_sha and repo_commits.repo_id like $repo_id group by weekday order by  weekday\n"
    }
   ]
  },
  {
   "title": "commits distribution in a week; ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "select dayofweek(authored_date) as weekday ,count(distinct commit_sha) as commit_nums from commits join repo_commits where commits.sha =repo_commits.commit_sha and repo_commits.repo_id like '%491450511%' group by weekday"
    }
   ]
  },
  {
   "title": "component dimension",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  }
 ]
}